### ISSUE TITLE
Cannot read property 'entries' of undefined

### ISSUE THREAD

**Issue by jordmsimm** [maurelian/dot-eth-js#30]
I am using the code below, and I am getting the error in the heading.

        var web3 = new Web3();
	web3.setProvider(new web3.providers.HttpProvider('http://localhost:8545'));

	var ens = new ENS(web3)

	var registrar = new Registrar(web3, ens, 'eth', 7,
	  function (err, txid) {
	    console.log(txid);
	  }
	);

	registrar.getEntry('insurance', function (err, result) {
	  console.log(result);
	});

**Comment by Arachnid** [comment]
Can you provide a complete stacktrace, please?

**Comment by seven3s** [comment]
I also encountered this problem
https://github.com/maurelian/eth-registrar-ens/issues/33

**Comment by seven3s** [comment]
fixed bug https://github.com/Arachnid/ensjs/pull/18

**Comment by jordmsimm** [comment]
Here is the full stack trace:

TypeError: Cannot read property 'entries' of undefined
    at Registrar.getEntry (/home/jordan/work/procryptix/ens-dapp/node_modules/eth-registrar-ens/lib/index.js:236:21)
    at /home/jordan/work/procryptix/ens-dapp/app.js:40:12
    at Layer.handle [as handle_request] (/home/jordan/work/procryptix/ens-dapp/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/jordan/work/procryptix/ens-dapp/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/jordan/work/procryptix/ens-dapp/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/jordan/work/procryptix/ens-dapp/node_modules/express/lib/router/layer.js:95:5)
    at /home/jordan/work/procryptix/ens-dapp/node_modules/express/lib/router/index.js:281:22
    at param (/home/jordan/work/procryptix/ens-dapp/node_modules/express/lib/router/index.js:354:14)
    at param (/home/jordan/work/procryptix/ens-dapp/node_modules/express/lib/router/index.js:365:14)
    at Function.process_params (/home/jordan/work/procryptix/ens-dapp/node_modules/express/lib/router/index.js:410:3)
    at next (/home/jordan/work/procryptix/ens-dapp/node_modules/express/lib/router/index.js:275:10)
    at SendStream.error (/home/jordan/work/procryptix/ens-dapp/node_modules/serve-static/index.js:121:7)
    at SendStream.emit (events.js:180:13)
    at SendStream.error (/home/jordan/work/procryptix/ens-dapp/node_modules/send/index.js:270:17)
    at SendStream.onStatError (/home/jordan/work/procryptix/ens-dapp/node_modules/send/index.js:421:12)
    at next (/home/jordan/work/procryptix/ens-dapp/node_modules/send/index.js:736:16)
